### ISSUE TITLE
Set up readthedocs.org

### ISSUE THREAD

**Issue by quantsini** [Yelp/pyswf#4]
We generate sphinx documentation as part of the default tox run, and outputs the documentation locally. Let's hook up readthedocs.org for hosted generated documentation.

**Comment by quantsini** [comment]
Documentation is live at http://py-swf.readthedocs.io/en/latest/?. All that's needed is to add the badge to README.rst!

**Comment by phishermaan** [comment]
fixed

**Comment by phishermaan** [comment]
add doc badge
